sudo: required
services:
  - docker

before_install:
  - docker build -t joheiss/client-test -f ./client/Dockerfile.dev ./client
  - docker build -t joheiss/server-test -f ./server/Dockerfile.dev ./server
  - docker build -t joheiss/worker-test -f ./worker/Dockerfile.dev ./worker

script:
 - docker run joheiss/client-test npm run test
 - docker run joheiss/server-test npm run test
 - docker run joheiss/worker-test npm run test

