version: '3'
services:
  # postgres database
  postgres:
    image: 'postgres:latest'
  # redis cache
  redis:
    image: 'redis:latest'
  api:
    image: 'joheiss/multi-server:latest'
    depends_on:
      - postgres
      - redis
  worker:
    image: 'joheiss/multi-worker:latest'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    image: 'joheiss/multi-client:latest'
    depends_on:
      - api
  nginx:
    restart: always
    image: 'joheiss/multi-nginx:latest'
    depends_on:
      - client
      - api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
